
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ Checker

POST http://localhost:3000/checker/steps/project/1
Accept: application/json
Content-Type: application/json

[
  {
    "id": 1,
    "user_id": 1,
    "user_record": { "step": 5, "mood": 45 },
    "project_id": 1,
    "resource_id": 50,
    "completed": false,
    "answers": [
      { "question_id": 1, "answer": 10 },
      { "question_id": 2, "answer": 10 },
      { "question_id": 3, "answer": 10 },
      { "question_id": 5, "answer": 5 }
    ]
  },{
    "id": 1,
    "user_id": 1,
    "user_record": { "step": 5, "mood": 45 },
    "project_id": 1,
    "resource_id": 50,
    "completed": false,
    "answers": [
      { "question_id": 1, "answer": 10 },
      { "question_id": 2, "answer": 10 },
      { "question_id": 3, "answer": 10 },
      { "question_id": 5, "answer": 5 }
    ]
  }
]


POST http://localhost:3000/checker/push/project/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "user_id": 1,
  "user_record": { "step": 1, "mood": 45 },
  "project_id": 1,
  "resource_id": 10,
  "completed": false,
  "answers": [
    { "question_id": 1, "answer": 10 },
    { "question_id": 2, "answer": 10 },
    { "question_id": 3, "answer": 10 },
    { "question_id": 5, "answer": 5 }
  ]
}

GET http://localhost:8000/api/v1/logic/checker
Accept: application/json
Authorization: Bearer 
Content-type: application/json

POST http://localhost:8000/api/v1/logic/checker/push
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "id": 1,
  "user_id": 1,
  "user_record": { "step": 4, "mood": 45 },
  "project_id": 1,
  "resource_id": 41,
  "completed": false,
  "answers": [
    { "question_id": 1, "answer": "10" },
    { "question_id": 2, "answer": "10" },
    { "question_id": 3, "answer": "10" },
    { "question_id": 5, "answer": "5" }
  ]
}

POST http://localhost:8000/api/v1/logic/checker/push
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "id": 1,
  "user_id": 1,
  "user_record": { "step": 5, "mood": 45 },
  "project_id": 1,
  "resource_id": 50,
  "completed": false,
  "answers": [
    { "question_id": 1, "answer": "10" },
    { "question_id": 2, "answer": "10" },
    { "question_id": 3, "answer": "10" },
    { "question_id": 5, "answer": "5" }
  ]
}

# }}}

# {{{ Scripts

# export TOKEN=$(curl http://localhost:8003/auth/bypass/1/ | jq .access_token | tr -d '\"')
# cat SCRIPTS/push_example.js | curl -H 'Authorization: Bearer '$TOKEN --data-binary @- http://localhost:8000/api/v1/logic/script/push/project/1
# cat SCRIPTS/cron_example.js | curl -H 'Authorization: Bearer '$TOKEN --data-binary @- http://localhost:8000/api/v1/logic/script/steps/project/1

# export TOKEN=$(curl http://localhost:8003/auth/bypass/1/ | jq .access_token | tr -d '\"')
# cat SCRIPTS/push_example.js | curl -H 'Authorization: Bearer '$TOKEN --data-binary @- http://localhost:8041/api/v1/logic/script/push/project/1
# cat SCRIPTS/cron_example.js | curl -H 'Authorization: Bearer '$TOKEN --data-binary @- http://localhost:8041/api/v1/logic/script/steps/project/1

GET http://localhost:8000/api/v1/logic/script/push/project/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

# }}}
